### ISSUE TITLE
ImagePicker and WebP-Support 

### ISSUE THREAD

**Issue by nurkka** [theo222/ImagePickerField#2]
First of all I would like to thank you for this great module!

Because of performance optimizations I had to activate WebP-Support according to these instructions: https://processwire.com/blog/posts/webp-images-and-more/#strategy-2-delivering-webp-and-automatically-falling-back-to-jpg-png
After that, outputting ImagePicker images did not work with newly uploaded images anymore.

### Short description of the issue

When activating WebP-Support in ProcessWire, the ImagePicker-Plugin Method "getImage" doesn't return the Image Object.

### Expected behavior

The method should return the image object.

### Actual behavior

The string comparison in the method getAImage in /ImagePickerField/InputfieldImagePicker.module fails, because it
compares the image path with ".jpg"-extension, with the image-object's url, which ends with ".webp".

### Suggestion for a possible fix
I modified the method getAImage in /ImagePickerField/InputfieldImagePicker.module and now it works.
This is just a quick and dirty fix for the issue.

```
	...
	if (is_object($img)) {

		// ::original::
		/*
		if (strpos($img->url, $imgpath) !== false) {
			$this->lastfieldtype = $f;
			return $img;
			break 2;
		}
		*/
		// ::/original::

		// ::modified::
		$imgurl_without_ext  = preg_replace('/(?:jpg|jpeg|png|gif|webp)$/i', '', $img->url);
		$imgpath_withour_ext = preg_replace('/(?:jpg|jpeg|png|gif|webp)$/i', '', $imgpath);
		if (strpos($imgurl_without_ext, $imgpath_withour_ext) !== false) {
			$this->lastfieldtype = $f;
			return $img;
			break 2;
		}
		// ::/modified::

	}
	...

```

### Steps to reproduce the issue

* Activate WebP-Support according to https://processwire.com/blog/posts/webp-images-and-more/#strategy-2-delivering-webp-and-automatically-falling-back-to-jpg-png .
* Upload a new Image e.g. to MediaLibrary.
* Go to a page with an ImagePicker-Field in the Backend, chose an image and save the page.
* Go to the frontend of that page and reload it.
* => The method getImage() will return NULL and therefore no image will be displayed.

### Setup/Environment
* ProcessWire version: 3.0.149 with activated WebP-Support
* (Optional) PHP version: 7.3

**Comment by theo222** [comment]
Commited without extensive testing.
Thank you!
